### ISSUE TITLE
Good Idea for this tutorial - Babel Polyfill

### ISSUE THREAD

**Issue by idkjs** [ceoworks/tutorial1-api-koa#1]
The project doesnt run when you clone, npm install, npm start. 

Im pretty sure its a babel polyfill error but i dont use gulp at all so cant really dig into it right now. Just an FYI. 

Are you planning on updating?

Here is the error if it helps:

```
/Users/projects/tutorial1-api-koa/dist/middlewares/handleErrors.js:6
	var _ref = _asyncToGenerator(regeneratorRuntime.mark(function _callee(ctx, next) {
	                             ^

ReferenceError: regeneratorRuntime is not defined
```

This post seems to be talking about the same thing: <http://stackoverflow.com/questions/34744953/how-to-use-babel-polyfill-in-gulpfile-js>

Best

**Comment by ceoworks** [comment]
thanks for issue, @idkjs !

I hope, it could be reproduced, then it would be fixed quickly)

Stay tuned :slightly_smiling_face:

**Comment by ceoworks** [comment]
Could you please also specify, what's your version of Node.js?
@idkjs

**Comment by idkjs** [comment]
@ceoworks I was using node 7.3 when i ran it. Thats the default on this machine.
